import Header from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import BgCircle from "@/components/BgCircle";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mihir-Dev",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body
        className={`${inter.className} bg-gray-50 text-gray-950 relative pt-28 sm:pt-36 overflow-x-hidden w-[100%]`}
        id="home"
      >
        <div className="bg-[#EE9322] absolute top-[-6rem] right-[4rem] h-[31.25rem] w-[27.25rem] blur-[20rem] rounded-full -z-20 sm:w-[68.75rem]"></div>
        <div className="bg-[#525FE1] -z-10 absolute top-[-1rem] blur-[20rem] left-[-35rem] h-[31.25rem] w-[50rem] rounded-full  sm:w-[68.75rem] md:left-[-33rem] lg:left-[-28rem] xl:left-[-15rem] 2xl:left-[-5rem] "></div>

        <Header />
        <Toaster position="top-right" reverseOrder={false} />
        {children}
        <Footer />
        <div className="bg-[#DA0C81] absolute bottom-[-3rem] right-[4rem] h-[31.25rem] w-[27.25rem] blur-[20rem] rounded-full -z-20 sm:w-[68.75rem]"></div>
        <div className="bg-[#5FBDFF] -z-10 absolute bottom-[-1rem] blur-[20rem] left-[-35rem] h-[31.25rem] w-[50rem] rounded-full  sm:w-[68.75rem] md:left-[-33rem] lg:left-[-28rem] xl:left-[-15rem] 2xl:left-[-5rem] "></div>
      </body>
    </html>
  );
}
